### PR TITLE
Refactor to cut down on operations/scratch usage

### PR DESCRIPTION
**Pull request by rreusser**
@Planeshifter, refactored this a bit to eliminate the need for scratch space and to move most of the operations inside cwise. It should perform somewhat faster. The only modification is that it doesn't explicitly set the upper-triangular portion of `L` to zero. I have mixed feelings on that.

Browserify works fine, but I'm totally unable to get the cwise browserify transform to work, so the test script is just `node test/test.js` in this branch. I've been cutting out everything possible, line by line, trying to isolate the problem but am unable to figure it out. It may have something to do with applying the cwise transform when some modules have already been transformed. @mikolalysenko, sorry to bug you, but any thoughts? Is cwise idempotent? The browserify error is not particularly helpful:

```
$ browserify -t cwise lib/index.js
Error: Parsing file /Users/rreusser/projects/scijs/rreusser/ndarray-ldl-factorization/lib/index.js: Unexpected token (9:0)
    at Deps.parseDeps (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:437:28)
    at fromSource (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:375:48)
    at /usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:370:17
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:117:20)
    at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DuplexWrapper.g (events.js:180:16)
```

### CODE REVIEW

**Comment by mikolalysenko** [comment]
Not sure yet, but one possibility is it could be a bug in [static-module](https://github.com/substack/static-module).  Will investigate this evening.  Also, cc @substack

**Comment by rreusser** [comment]
Thanks. And almost forgot: Got here in the first place because the coverify transform still fails on cwise when the cwise transform is ommitted:

```
npm test

> ndarray-ldl-factorization@1.0.6 test /Users/rreusser/projects/scijs/rreusser/ndarray-ldl-factorization
> browserify -t coverify test/test.js --bare | node | ./node_modules/.bin/coverify


[stdin]:861
      throw new Error("cwise-parser: Computed this is not allowed")
            ^
Error: cwise-parser: Computed this is not allowed
    at visit ([stdin]:861:13)
    at visit ([stdin]:900:17)
    at visit ([stdin]:858:9)
    at visit ([stdin]:904:13)
    at visit ([stdin]:900:17)
    at visit ([stdin]:904:13)
    at visit ([stdin]:900:17)
    at visit ([stdin]:900:17)
    at preprocess ([stdin]:909:5)
    at createCWise ([stdin]:113:17)
# /Users/rreusser/projects/scijs/rreusser/ndarray-ldl-factorization/test/test.js: line 28, column -157-3, -157-3, -157-3

  
  test( 'should export a function', function test(t) {
  	var isFunction = typeof ldl === 'function';
  	t.assert(isFunction, 'it is indeed a function');
  	t.end();
  });
  test('returns false if provided non-square matrix',function test(t) {
  
  	var A = ndarray(new Float64Array([1,2,2,4,8,6]), [2, 3]);
  	var L = pool.zeros( A.shape, A.dtype );
  	var d = pool.zeros( [ A.shape[0] ], A.dtype);
  	var result = ldl(A, L, d);
  
  	t.notOk(result, 'returns false');
  	t.end();
  });
  test('returns false if provided higher-dimensional array (dim > 2)',function test(t) {
  
  	t.plan(1);
  	var A = ndarray(new Float64Array([1,2,3,4,5,6,7,8]), [2,2,2]);
  	var L = pool.zeros( A.shape, A.dtype );
  	var d = pool.zeros( [ A.shape[0] ], A.dtype);
  	var result = ldl(A, L, d);
  
  	t.notOk(result, 'returns false');
  	t.end();
  });
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# /Users/rreusser/projects/scijs/rreusser/ndarray-ldl-factorization/test/test.js: line 45, column -656-4

  
  test( 'should calculate the LDL decomposition of matrix A', function test(t) {
  
  	var A = ndarray(new Float64Array([9,-1,2,-1,8,-5,2,-5,7]), [3,3]);
  	var L = pool.zeros( A.shape, A.dtype );
  	var d = pool.zeros( [ A.shape[0] ], A.dtype);
  
  	var isTrue = ldl(A, L, d);
  	t.assert(isTrue, 'ldl returns true');
  
  	var LExpected = ndarray(new Float64Array([1,0,0,-0.111,1,0,0.222,-0.606,1]), [3,3]);
  	t.assert( ndt.approximatelyEqual(L, LExpected, 1e-3), 'L is correctly calculated' );
  
  	var d_expected = ndarray(new Float64Array([9, 7.889, 3.662]), [3]);
  	t.assert( ndt.approximatelyEqual(d, d_expected, 1e-3), 'elements of D are correctly calculated' );
  	t.end();
  } );
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# /Users/rreusser/projects/scijs/rreusser/ndarray-ldl-factorization/lib/index.js: line 14, column 5-17

      this.sum = 0;
      ^^^^^^^^^^^^^

# /Users/rreusser/projects/scijs/rreusser/ndarray-ldl-factorization/lib/index.js: line 17, column 5-26

      this.sum += a * a * b;
      ^^^^^^^^^^^^^^^^^^^^^^

# /Users/rreusser/projects/scijs/rreusser/ndarray-ldl-factorization/lib/index.js: line 35, column -207-3

  
  var threeWayDot = cwise({
    args:['array','array', 'array'],
    pre: function() {
      this.sum = 0;
    },
    body: function(a,b,c) {
      this.sum += a * b * c;
    },
    post: function() {
      return this.sum;
    }
  });
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# coverage: 206/213 (96.71 %)

npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by mikolalysenko** [comment]
Also weird, though that is definitely a bug in cwise.  May also want to get @jaspervdg to check this out.

**Comment by rreusser** [comment]
Thanks for you attention to the issue! Hope I'm not turning into an aggravator!

**Comment by mikolalysenko** [comment]
I'm just glad to discover these sorts of bugs.  cwise needs lots more of this kind of attention to get it to 100%

**Comment by rreusser** [comment]
Bug report + test case filed at: scijs/cwise-parser#3

**Comment by Planeshifter** [comment]
Thanks for improving the code! I guess we should wait with merging until the cwise bug is fixed?

**Comment by rreusser** [comment]
Yeah, maybe so. No dependents (or users :frowning: ) at the moment so no rush, I guess. But yeah, would be nice to straighten that out.

**Comment by rreusser** [comment]
Okay, I've rewritten this as a major version bump since I removed the automatic zeroing of the whole matrix. Other than that though, the behavior is the same and it now works both out-of-place (`ldl(A,L,d)`) and in-place (`ldl(A,A,diag(A))`). Unfortunately I didn't get coverify working again, but I'm going to merge this and move coverify to a separate issue since this has been pending for like two and a half months (my fault for offering to help and not carrying through :frowning: )

**Comment by rreusser** [comment]
Also, @Planeshifter, please let me know if I've done anything rude here by merging a pull request into a repo you created! It took me a while to realize that cwise was totally unnecessary for vector operations, and the addition of in-place factorization, preservation of existing tests, and general stalling of progress on this matrix stuff (:frowning:) suggested that it made sense to go ahead and merge it. But I don't want to step on toes. On an unrelated note, nice work on the distribution stuff, btw. It's impressively comprehensive!

**Comment by Planeshifter** [comment]
@rreusser Not at all, thanks for the kind words and for rewriting and thereby improving the package!

**Pull request merged**
